server:
  port: 8013

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: org.study.entity    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mapper/*.xml                       # mapper映射文件

spring:
   application:
    name: microservice-provider
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb03             # 数据库名称
    username: root
    password: 333333
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200
#debug: true                                 # 等待连接获取的最大超时时间
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka  #单机版eureka
      defaultZone: http://eurekaa.com:7011/eureka/,http://eurekab.com:7012/eureka/,http://eurekac.com:7013/eureka/  #eureka集群
  instance:
    instance-id: microservice-provider-03
    prefer-ip-address: true
info:
  app.name: study-microservice
  company.name: www.pactera.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$